- hosts: localhost
  vars:
    main_user: "{{ main_user }}"
    root_user: root
    temp_dir: "/home/{{ main_user }}/linux-636-temp/"
  become: true
  become_user: "{{ main_user }}"

  # Setup
  pre_tasks:
    - name: Create Temp Directory
      ansible.builtin.file:
        path: "{{ temp_dir }}"
        state: directory
        mode: 0755
      become: true
      become_user: "{{ main_user }}"
    - name: Update Apt Repositories
      ansible.builtin.apt:
        update_cache: yes
      become: true
      become_user: "{{ root_user }}"

  # Run Scripts
  tasks:
    - import_tasks: ./tasks/install_apts.yml
    # - import tasks: ./tasks/install_bluebubbles.yml
    - import_tasks: ./tasks/install_chrome.yml
    # - import_tasks: ./tasks/install_discord.yml
    - import_tasks: ./tasks/install_docker.yml
    # - import_tasks: ./tasks/install_eclipse.yml
    # - import_tasks: ./tasks/install_freecad.yml
    - import_tasks: ./tasks/install_pop_shell.yml
    # - import_tasks: ./tasks/install_python.yml
    - import_tasks: ./tasks/install_snaps.yml
    - import_tasks: ./tasks/install_vscode.yml

  # Cleanup
  post_tasks:
    - name: Cleanup Temp Directory
      ansible.builtin.file:
        path: "{{ temp_dir }}"
        state: absent
      become: true
      become_user: "{{ root_user }}"