- hosts: localhost
  vars:
    main_user: "{{ main_user }}"
    root_user: root
  become: true
  become_user: "{{ main_user }}"
  pre_tasks:
    - name: Update Apt Repositories
      become: true
      become_user: root
      apt: update_cache=yes
      changed_when: False

  tasks:
    - import_tasks: ./tasks/install_apts.yml
    - import_tasks: ./tasks/install_chrome.yml
    - import_tasks: ./tasks/install_docker.yml
    - import_tasks: ./tasks/install_freecad.yml
    - import_tasks: ./tasks/install_node.yml
    - import_tasks: ./tasks/install_snaps.yml
    - import_tasks: ./tasks/install_vscode.yml
    - import_tasks: ./tasks/install_python.yml
    # TODO - Install Discord
    # TODO - Install Git LFS