- name: Add NodeJS GPG Key
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present
  become: true
  become_user: "{{ root_user }}"

- name: Install NodeJS Repo
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_16.x {{ ansible_lsb.codename }} main"
    state: present
    update_cache: true
  become: true
  become_user: "{{ root_user }}"

- name: Install NodeJS
  apt:
    name: nodejs
    state: latest
  become: true
  become_user: "{{ root_user }}"
