# Thanks Peter - https://github.com/peterHoburg/workstation_setup/blob/main/tasks/install_python_poetry.yml
# https://python-poetry.org/docs/master/#installing-with-the-official-installer
- name: Download Poetry Install Script
  get_url:
    url: https://install.python-poetry.org
    dest: "/home/{{ main_user }}/Downloads/install-poetry.py"
    mode: '0777'
  become: true
  become_user: "{{ main_user }}"

- name: Run Poetry Install Script
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.script:
    cmd: "/home/{{ main_user }}/Downloads/install-poetry.py"
  args:
    creates: /home/{{ main_user }}/.local/bin/poetry
    executable: python3

# TODO - Pyenv
