- name: Install Packages
  ansible.builtin.apt:
    pkg:
      - git
      - git-lfs
      - curl
      - software-properties-common
      - apt-transport-https
      - wget
      - libcanberra-gtk-module
      - default-jdk
      - gnome-tweaks
      - gnome-shell-extensions
      - vim
      - zeal
      - filezilla
      - build-essential
      - transmission-gtk
      - tree
      - hexchat
      - gimp
      - rawtherapee
      - libreoffice
      - virtualbox
      - gcc
      - g++
      - make
      - node-typescript
      - libnotify-dev
      - libappindicator3-dev
      - gnome-shell-extension-appindicator
      - vlc 
      - libvlc-dev 
      - rclone
    state: latest
  become: true
  become_user: "{{ root_user }}"
