- name: Install Apt Packages
  ansible.builtin.apt:
    pkg:
      - git
      - git-lfs
      - curl
      - software-properties-common
      - apt-transport-https
      - wget
      - libcanberra-gtk-module
      - default-jdk
      - gnome-tweaks
      - gnome-shell-extensions
      - vim
      - zeal
      - filezilla
      - build-essential
      - transmission-gtk
      - tree
      - hexchat
      - gimp
      - rawtherapee
      - libreoffice
      - virtualbox
      - gcc
      - g++
      - make
      - node-typescript
      - rclone
      - thunderbird
      - flatpak
      - gnome-software-plugin-flatpak
    state: latest
  become: true
  become_user: "{{ root_user }}"

- name: Add VSCode GPG Key
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present
  become: true
  become_user: "{{ root_user }}"

- name: Install VSCode Repo
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    state: present
    update_cache: true
  become: true
  become_user: "{{ root_user }}"

- name: Install VSCode
  apt:
    name: code
    state: latest
  become: true
  become_user: "{{ root_user }}"
